name: Publish NPM Package

on:
  push:
    branches:
      - ci/cd

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install

      - name: Determine version type
        run: |
          commit_message_body=$(git log -1 --pretty=%B | grep -Eio '^(fix|feat|breaking)')
          echo "commit_message_body=$commit_message_body" >> $GITHUB_ENV
          if [[ ${commit_message_body} == "breaking" ]]; then
            echo "versionType=major" >> $GITHUB_ENV
          elif [[ ${commit_message_body} == "feat" ]]; then
            echo "versionType=minor" >> $GITHUB_ENV
          else 
            echo "versionType=patch" >> $GITHUB_ENV
          fi

      - uses: actions/checkout@v2
      - run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - run: git config --global user.name "$GITHUB_ACTOR"
      - run: |
          npm version $versionType -m "Bump version to %s [skip ci]" -d
          echo "$versionType"
      - run: VERSION=$(node -p "require('./package.json').version")
      - run: git tag ${VERSION}
      - run: git push origin --tags
      - run: git push origin --follow-tags
